[project]
name = "pyconsole"
version = "0.1.0"
description = "Self-contained Python app with urllib3 HTTP requests"
requires-python = ">=3.8"
dependencies = [
    "urllib3>=2.0.0"
]

[tool.uv]
dev-dependencies = [
    "pyinstaller>=6.0.0"
]